mage: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_16:202106191213

stages:
    - unit_tests
    - integration_tests
    - coverage
    - report
    - scan
    - deploy

unit_tests:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - echo $GOPATH
    - pwd
    - make test

race_detector:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make race

memory_sanitizer:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make msan

lint_code:
  stage: unit_tests
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make lint

integration_tests:
  stage: integration_tests
  services:
    - name: registry.windmaker.net:5005/a-castellano/limani/base_rabbitmq_server:202104052102
      alias: rabbitmq
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make test_integration

coverage:
  stage: coverage
  services:
    - name: registry.windmaker.net:5005/a-castellano/limani/base_rabbitmq_server:202104052102
      alias: rabbitmq
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make coverage
  coverage: /total:\s+.+\s(\d+\.\d+?)%$/
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - cover
    expire_in: 1 hour

code_coverage_report:
  stage: report
  services:
    - name: registry.windmaker.net:5005/a-castellano/limani/base_rabbitmq_server:202104052102
      alias: rabbitmq
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-job-router
    - cd $GOPATH/src/github.com/a-castellano/music-manager-job-router
  script:
    - make coverhtml
  dependencies:
  - coverage
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - coverage.html
      - cover
    expire_in: 1 hour


