[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
  
  [wrappers.secondwrapper]
  name = "secondwrapper"

[wrapperoutput]
name = "wrapperoutput"

[jobmanager]
name = "jobmanager"

[status]
name = "status"

[storage]
namee = "storage"
