[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
 
[status]
name = "status"
durable = true
delete_when_unused = false
exclusive = false
no_wait = false
auto_ack = false

[storage]
name = "storage"
durable = true
delete_when_unused = false
exclusive = false
no_wait = false
auto_ack = false
 
