[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

  [wrappers.firstwrapper]
  namee = "firstwrapper"

[jobs]
name = "jobs"

[status]
name = "status"

[storage]
name = "storage"
