[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
  
  [wrappers.secondwrapper]
  name = "secondwrapper"

[jobmanager]
name = "jobmanager"
durable = true
delete_when_unused = false
exclusivee = false
no_wait = false
auto_ack = false


[storage]
name = "storage"
