[server]

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
  
  [wrappers.secondwrapper]
  name = "secondwrapper"

[jobmanager]
name = "jobmanager"

[status]
name = "status"

[storage]
name = "storage"
