[server]

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
  durable = true
  delete_when_unused = false
  exclusive = false
  no_wait = false
  auto_ack = false
  
  [wrappers.secondwrapper]
  name = "secondwrapper"
  durable = true
  delete_when_unused = false
  exclusive = false
  no_wait = false
  auto_ack = false

[jobmanager]
name = "jobmanager"
durable = true
delete_when_unused = false
exclusivee = false
no_wait = false
auto_ack = false

[status]
name = "status"

[storage]
name = "storage"
