[server]

[wrappers]

  [wrappers.firstwrapper]
  name = "firstwrapper"
  
  [wrappers.secondwrapper]
  name = "secondwrapper"

[wrapperoutput]
name = "wrapperoutput"

[jobmanager]
name = "jobmanager"

[status]
name = "status"

[storage]
name = "storage"
