[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

[wrapperoutput]
name = "wrapperoutput"

[jobmanager]
name = "jobmanager"

[status]
name = "status"

[storage]
name = "storage"
