[server]

host = "localhost"
port = 5672
user = "guest"
password = "pass"

[wrappers]

[jobs]
name = "jobs"
durable = true
delete_when_unused = false
exclusivee = false
no_wait = false
auto_ack = false

[status]
name = "status"

[storage]
name = "storage"
